// <auto-generated />
using System;
using FirmaCurierat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirmaCurierat.Migrations
{
    [DbContext(typeof(FirmaCurieratContext))]
    [Migration("20260421154550_ModificareAdresaOptionala")]
    partial class ModificareAdresaOptionala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirmaCurierat.Models.Adresa", b =>
                {
                    b.Property<int>("Id_adresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_adresa"));

                    b.Property<int>("ClientId_client")
                        .HasColumnType("int");

                    b.Property<int?>("Id_client")
                        .HasColumnType("int");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_adresa");

                    b.HasIndex("ClientId_client");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Angajat", b =>
                {
                    b.Property<int>("Id_angajat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_angajat"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_angajat");

                    b.ToTable("Angajati");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Angajat");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FirmaCurierat.Models.Client", b =>
                {
                    b.Property<int>("Id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_client"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_client");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Colet", b =>
                {
                    b.Property<int>("Id_colet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_colet"));

                    b.Property<string>("Awb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComandaId_comanda")
                        .HasColumnType("int");

                    b.Property<string>("Dimensiune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Greutate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Id_comanda")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_colet");

                    b.HasIndex("ComandaId_comanda");

                    b.ToTable("Colete");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Comanda", b =>
                {
                    b.Property<int>("Id_comanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_comanda"));

                    b.Property<int>("HubId_hub")
                        .HasColumnType("int");

                    b.Property<int>("Id_adresa_livrare")
                        .HasColumnType("int");

                    b.Property<int>("Id_adresa_ridicare")
                        .HasColumnType("int");

                    b.Property<int?>("Id_curier")
                        .HasColumnType("int");

                    b.Property<int>("Id_destinatar")
                        .HasColumnType("int");

                    b.Property<int>("Id_expeditor")
                        .HasColumnType("int");

                    b.Property<int?>("Id_hub")
                        .HasColumnType("int");

                    b.Property<int?>("Id_operator")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_comanda");

                    b.HasIndex("HubId_hub");

                    b.HasIndex("Id_adresa_livrare");

                    b.HasIndex("Id_adresa_ridicare");

                    b.HasIndex("Id_curier");

                    b.HasIndex("Id_destinatar");

                    b.HasIndex("Id_expeditor");

                    b.HasIndex("Id_operator");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Conduce", b =>
                {
                    b.Property<int>("Id_conduce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_conduce"));

                    b.Property<int>("Id_curier")
                        .HasColumnType("int");

                    b.Property<int>("Id_vehicul")
                        .HasColumnType("int");

                    b.Property<int>("VehiculId_vehicul")
                        .HasColumnType("int");

                    b.HasKey("Id_conduce");

                    b.HasIndex("Id_curier");

                    b.HasIndex("VehiculId_vehicul");

                    b.ToTable("Conduceri");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Factura", b =>
                {
                    b.Property<int>("Id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_factura"));

                    b.Property<int>("ClientId_client")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_client")
                        .HasColumnType("int");

                    b.Property<int>("Id_comanda")
                        .HasColumnType("int");

                    b.Property<decimal>("Valoare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_factura");

                    b.HasIndex("ClientId_client");

                    b.HasIndex("Id_comanda");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Hub", b =>
                {
                    b.Property<int>("Id_hub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_hub"));

                    b.Property<int>("Capacitate")
                        .HasColumnType("int");

                    b.Property<int?>("Id_adresa")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_hub");

                    b.HasIndex("Id_adresa");

                    b.ToTable("Huburi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.StatusLivrare", b =>
                {
                    b.Property<int>("Id_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_status"));

                    b.Property<int>("ColetId_colet")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_colet")
                        .HasColumnType("int");

                    b.HasKey("Id_status");

                    b.HasIndex("ColetId_colet");

                    b.ToTable("StatusuriLivrare");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Tranziteaza", b =>
                {
                    b.Property<int>("Id_tranziteaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_tranziteaza"));

                    b.Property<int>("Id_colet")
                        .HasColumnType("int");

                    b.Property<int>("Id_hub")
                        .HasColumnType("int");

                    b.HasKey("Id_tranziteaza");

                    b.HasIndex("Id_colet");

                    b.HasIndex("Id_hub");

                    b.ToTable("Tranzitari");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Vehicul", b =>
                {
                    b.Property<int>("Id_vehicul")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_vehicul"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_vehicul");

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Curier", b =>
                {
                    b.HasBaseType("FirmaCurierat.Models.Angajat");

                    b.Property<string>("Categorie_permis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Curier");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Operator", b =>
                {
                    b.HasBaseType("FirmaCurierat.Models.Angajat");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Operator");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Adresa", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Client", "Client")
                        .WithMany("Adrese")
                        .HasForeignKey("ClientId_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Colet", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Comanda", "Comanda")
                        .WithMany("Colete")
                        .HasForeignKey("ComandaId_comanda");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Comanda", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Hub", "Hub")
                        .WithMany("Comenzi")
                        .HasForeignKey("HubId_hub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Adresa", "AdresaLivrare")
                        .WithMany()
                        .HasForeignKey("Id_adresa_livrare")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Adresa", "AdresaRidicare")
                        .WithMany()
                        .HasForeignKey("Id_adresa_ridicare")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Curier", "Curier")
                        .WithMany()
                        .HasForeignKey("Id_curier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmaCurierat.Models.Client", "Destinatar")
                        .WithMany("ComenziPrimite")
                        .HasForeignKey("Id_destinatar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Client", "Expeditor")
                        .WithMany("ComenziExpediate")
                        .HasForeignKey("Id_expeditor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("Id_operator")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdresaLivrare");

                    b.Navigation("AdresaRidicare");

                    b.Navigation("Curier");

                    b.Navigation("Destinatar");

                    b.Navigation("Expeditor");

                    b.Navigation("Hub");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Conduce", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Curier", "Curier")
                        .WithMany()
                        .HasForeignKey("Id_curier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Vehicul", "Vehicul")
                        .WithMany("Conduceri")
                        .HasForeignKey("VehiculId_vehicul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curier");

                    b.Navigation("Vehicul");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Factura", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Client", "Client")
                        .WithMany("Facturi")
                        .HasForeignKey("ClientId_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Comanda", "Comanda")
                        .WithMany("Facturi")
                        .HasForeignKey("Id_comanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Hub", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("Id_adresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Adresa");
                });

            modelBuilder.Entity("FirmaCurierat.Models.StatusLivrare", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Colet", "Colet")
                        .WithMany("Statusuri")
                        .HasForeignKey("ColetId_colet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colet");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Tranziteaza", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Colet", "Colet")
                        .WithMany("Tranzitari")
                        .HasForeignKey("Id_colet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Hub", "Hub")
                        .WithMany("Tranzitari")
                        .HasForeignKey("Id_hub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colet");

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Client", b =>
                {
                    b.Navigation("Adrese");

                    b.Navigation("ComenziExpediate");

                    b.Navigation("ComenziPrimite");

                    b.Navigation("Facturi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Colet", b =>
                {
                    b.Navigation("Statusuri");

                    b.Navigation("Tranzitari");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Comanda", b =>
                {
                    b.Navigation("Colete");

                    b.Navigation("Facturi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Hub", b =>
                {
                    b.Navigation("Comenzi");

                    b.Navigation("Tranzitari");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Vehicul", b =>
                {
                    b.Navigation("Conduceri");
                });
#pragma warning restore 612, 618
        }
    }
}
