// <auto-generated />
using System;
using FirmaCurierat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirmaCurierat.Migrations
{
    [DbContext(typeof(FirmaCurieratContext))]
    partial class FirmaCurieratContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirmaCurierat.Models.Adresa", b =>
                {
                    b.Property<int>("Id_adresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_adresa"));

                    b.Property<int?>("Id_client")
                        .HasColumnType("int");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_adresa");

                    b.HasIndex("Id_client");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Angajat", b =>
                {
                    b.Property<int>("Id_angajat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_angajat"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_angajat");

                    b.ToTable("Angajati");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Angajat");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FirmaCurierat.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PozaProfil")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FirmaCurierat.Models.Client", b =>
                {
                    b.Property<int>("Id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_client"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_client");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Colet", b =>
                {
                    b.Property<int>("Id_colet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_colet"));

                    b.Property<string>("Awb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComandaId_comanda")
                        .HasColumnType("int");

                    b.Property<decimal>("CostLivrare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dimensiune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Greutate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Id_comanda")
                        .HasColumnType("int");

                    b.Property<int?>("Id_tarif")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TarifId_tarif")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaLivrare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_colet");

                    b.HasIndex("ComandaId_comanda");

                    b.HasIndex("TarifId_tarif");

                    b.ToTable("Colete");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Comanda", b =>
                {
                    b.Property<int>("Id_comanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_comanda"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_adresa_livrare")
                        .HasColumnType("int");

                    b.Property<int>("Id_adresa_ridicare")
                        .HasColumnType("int");

                    b.Property<int?>("Id_curier")
                        .HasColumnType("int");

                    b.Property<int>("Id_destinatar")
                        .HasColumnType("int");

                    b.Property<int>("Id_expeditor")
                        .HasColumnType("int");

                    b.Property<int?>("Id_hub")
                        .HasColumnType("int");

                    b.Property<int?>("Id_operator")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_comanda");

                    b.HasIndex("Id_adresa_livrare");

                    b.HasIndex("Id_adresa_ridicare");

                    b.HasIndex("Id_curier");

                    b.HasIndex("Id_destinatar");

                    b.HasIndex("Id_expeditor");

                    b.HasIndex("Id_hub");

                    b.HasIndex("Id_operator");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Conduce", b =>
                {
                    b.Property<int>("Id_conduce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_conduce"));

                    b.Property<int>("Id_curier")
                        .HasColumnType("int");

                    b.Property<int>("Id_vehicul")
                        .HasColumnType("int");

                    b.Property<int>("VehiculId_vehicul")
                        .HasColumnType("int");

                    b.HasKey("Id_conduce");

                    b.HasIndex("Id_curier");

                    b.HasIndex("VehiculId_vehicul");

                    b.ToTable("Conduceri");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Contact", b =>
                {
                    b.Property<int>("Id_contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_contact"));

                    b.Property<string>("Detalii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_contact");

                    b.ToTable("Contacte");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Factura", b =>
                {
                    b.Property<int>("Id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_factura"));

                    b.Property<int>("ClientId_client")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_client")
                        .HasColumnType("int");

                    b.Property<int>("Id_comanda")
                        .HasColumnType("int");

                    b.Property<decimal>("Valoare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_factura");

                    b.HasIndex("ClientId_client");

                    b.HasIndex("Id_comanda");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Hub", b =>
                {
                    b.Property<int>("Id_hub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_hub"));

                    b.Property<int>("Capacitate")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_hub");

                    b.ToTable("Huburi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.StatusLivrare", b =>
                {
                    b.Property<int>("Id_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_status"));

                    b.Property<DateTime>("Data_actualizare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_colet")
                        .HasColumnType("int");

                    b.Property<string>("Locatie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_status");

                    b.HasIndex("Id_colet");

                    b.ToTable("StatusuriLivrare");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Tarif", b =>
                {
                    b.Property<int>("Id_tarif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_tarif"));

                    b.Property<string>("CategorieGreutate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretInternational")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PretLocal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PretNational")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_tarif");

                    b.ToTable("Tarife");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Tranziteaza", b =>
                {
                    b.Property<int>("Id_tranziteaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_tranziteaza"));

                    b.Property<int>("Id_colet")
                        .HasColumnType("int");

                    b.Property<int>("Id_hub")
                        .HasColumnType("int");

                    b.HasKey("Id_tranziteaza");

                    b.HasIndex("Id_colet");

                    b.HasIndex("Id_hub");

                    b.ToTable("Tranzitari");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Vehicul", b =>
                {
                    b.Property<int>("Id_vehicul")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_vehicul"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_vehicul");

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FirmaCurierat.Models.Curier", b =>
                {
                    b.HasBaseType("FirmaCurierat.Models.Angajat");

                    b.Property<string>("Categorie_permis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Curier");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Operator", b =>
                {
                    b.HasBaseType("FirmaCurierat.Models.Angajat");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Operator");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Adresa", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Client", "Client")
                        .WithMany("Adrese")
                        .HasForeignKey("Id_client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Colet", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Comanda", "Comanda")
                        .WithMany("Colete")
                        .HasForeignKey("ComandaId_comanda");

                    b.HasOne("FirmaCurierat.Models.Tarif", "Tarif")
                        .WithMany("Colete")
                        .HasForeignKey("TarifId_tarif");

                    b.Navigation("Comanda");

                    b.Navigation("Tarif");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Comanda", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Hub", "Hub")
                        .WithMany("Comenzi")
                        .HasForeignKey("Id_hub")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmaCurierat.Models.Adresa", "AdresaLivrare")
                        .WithMany()
                        .HasForeignKey("Id_adresa_livrare")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Adresa", "AdresaRidicare")
                        .WithMany()
                        .HasForeignKey("Id_adresa_ridicare")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Curier", "Curier")
                        .WithMany()
                        .HasForeignKey("Id_curier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmaCurierat.Models.Client", "Destinatar")
                        .WithMany("ComenziPrimite")
                        .HasForeignKey("Id_destinatar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Client", "Expeditor")
                        .WithMany("ComenziExpediate")
                        .HasForeignKey("Id_expeditor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("Id_operator")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdresaLivrare");

                    b.Navigation("AdresaRidicare");

                    b.Navigation("Curier");

                    b.Navigation("Destinatar");

                    b.Navigation("Expeditor");

                    b.Navigation("Hub");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Conduce", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Curier", "Curier")
                        .WithMany()
                        .HasForeignKey("Id_curier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Vehicul", "Vehicul")
                        .WithMany("Conduceri")
                        .HasForeignKey("VehiculId_vehicul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curier");

                    b.Navigation("Vehicul");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Factura", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Client", "Client")
                        .WithMany("Facturi")
                        .HasForeignKey("ClientId_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Comanda", "Comanda")
                        .WithMany("Facturi")
                        .HasForeignKey("Id_comanda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("FirmaCurierat.Models.StatusLivrare", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Colet", "Colet")
                        .WithMany("Statusuri")
                        .HasForeignKey("Id_colet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colet");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Tranziteaza", b =>
                {
                    b.HasOne("FirmaCurierat.Models.Colet", "Colet")
                        .WithMany("Tranzitari")
                        .HasForeignKey("Id_colet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.Hub", "Hub")
                        .WithMany("Tranzitari")
                        .HasForeignKey("Id_hub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colet");

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FirmaCurierat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FirmaCurierat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaCurierat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FirmaCurierat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirmaCurierat.Models.Client", b =>
                {
                    b.Navigation("Adrese");

                    b.Navigation("ComenziExpediate");

                    b.Navigation("ComenziPrimite");

                    b.Navigation("Facturi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Colet", b =>
                {
                    b.Navigation("Statusuri");

                    b.Navigation("Tranzitari");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Comanda", b =>
                {
                    b.Navigation("Colete");

                    b.Navigation("Facturi");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Hub", b =>
                {
                    b.Navigation("Comenzi");

                    b.Navigation("Tranzitari");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Tarif", b =>
                {
                    b.Navigation("Colete");
                });

            modelBuilder.Entity("FirmaCurierat.Models.Vehicul", b =>
                {
                    b.Navigation("Conduceri");
                });
#pragma warning restore 612, 618
        }
    }
}
